### ISSUE TITLE
update black requirement from ^23.10.1 to ^24.1.1

### ISSUE THREAD

**Issue by callmenemo491** [stuckatsixpm/antelopy#10]
i forked and added a dependabot.
it reported these recommendations

* update black requirement from ^23.10.1 to ^24.1.1

Updates the requirements on [black](https://github.com/psf/black) to permit the latest version.
- [Release notes](https://github.com/psf/black/releases)
- [Changelog](https://github.com/psf/black/blob/main/CHANGES.md)
- [Commits](https://github.com/psf/black/compare/23.10.1...24.1.1)

pyproject.toml
change:
`black = "^23.10.1"`
to:
`black = "^24.1.1"`

**Comment by stuckatsixpm** [comment]
Thanks for letting me know.

`black` and `pylint` are both optional development dependencies for code quality, but I'll update dependencies when needed.
