### ISSUE TITLE
update pytest requirement from ^7.4.3 to ^8.0.0

### ISSUE THREAD

**Issue by callmenemo491** [stuckatsixpm/antelopy#9]
i forked and added a dependabot.
it reported these recommendations

* update pytest requirement from ^7.4.3 to ^8.0.0

Updates the requirements on [pytest](https://github.com/pytest-dev/pytest) to permit the latest version.
- [Release notes](https://github.com/pytest-dev/pytest/releases)
- [Changelog](https://github.com/pytest-dev/pytest/blob/main/CHANGELOG.rst)
- [Commits](https://github.com/pytest-dev/pytest/compare/7.4.3...8.0.0)

**pyproject.toml**
change:
`pytest = "^7.4.3"`
to:
`pytest = "^8.0.0"`

**Comment by stuckatsixpm** [comment]
(See #10 for more info)
